name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests - get suite
      run: |
        pytest --suite=get_test_suite --html=pytest_report_get.html --self-contained-html

    - name: Run tests - post suite
      run: |
        pytest --suite=post_test_suite --html=pytest_report_post.html --self-contained-html
    
    - name: Run tests - put suite
      run: |
        pytest --suite=put_test_suite --html=pytest_report_put.html --self-contained-html

    - name: Run tests - delete suite
      run: |
        pytest --suite=delete_test_suite --html=pytest_report_put.html --self-contained-html

    - name: Upload HTML report - get suite
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report_get
        path: reports/
    
    - name: Upload HTML report - post suite
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report_post
        path: reports/

    - name: Upload HTML report - put suite
      uses: actions/upload-artifact@v3
      with:
        name: pytest-report_put
        path: reports/

    - name: Upload HTML report - delete suite
      uses: actions/upload-artifact@v3
      with:
          name: pytest-report_delete
          path: reports/